config/routes.rb
Rails.application.routes.draw do
  #get routes
  get'static_pages/html'
  get 'static_pages/development'
  get 'ac_demos/home'
  get 'ar/has_one', as: :ar_one
  get 'ar/has_many', as: :ar_hm
  get 'ar/has_many_through', as: :ar_hm_through
  get 'ar/belongs_to', as: :ar_belongs_to
  get 'ar/home', as: :ar_home
  get 'populator', to: 'gem_demos#form_populator'
  #root
  root to: 'static_pages#home'

  #CRUD
  resources :gem_demos
  resources :ac_demos
  # get '/home', to: 'static_pages/home', as: 'home'
  # get '/js', to: 'static_pages/ja', as: 'javascript'
  # get '/development', to: 'static_pages/development', as: 'development'
  # root to: '/html', to: 'static_pages#html', as: 'html'

end

app/models/ac_demo.rb
class AcDemo < ActiveRecord::Base
  validates :title, presence: true
end

app/models/contract.rb
class Contract < ActiveRecord::Base
  belongs_to :couple
  belongs_to :vendor
end

app/models/couple.rb
class Couple < ActiveRecord::Base
  has_many :contracts
    has_many :vendors, through: :contracts
end

app/models/doctor.rb
class Doctor < ActiveRecord::Base
  belongs_to :userhm
end

app/models/gem_demo.rb
class GemDemo < ActiveRecord::Base
  validates :first_name, presence: true
end

app/models/has_one1.rb
class HasOne1 < ActiveRecord::Base
  has_one :has_one_b
end

app/models/has_one_b.rb
class HasOneB < ActiveRecord::Base
  belongs_to :has_one1
end

app/models/userhm.rb
class Userhm < ActiveRecord::Base
  has_many :doctors
end

app/models/vendor.rb
class Vendor < ActiveRecord::Base
  has_many :contracts
    has_many :couples, through: :contracts
end

app/controllers/ac_demos_controller.rb
class AcDemosController < ApplicationController
  before_action :demo, only: [:show, :edit, :update, :destroy]
  def home
    @ac_demos = AcDemo.all
  end

  def index
    @ac_demos = AcDemo.all
  end

  def new
    @ac_demo = AcDemo.new
  end

  def create
    @ac_demo = AcDemo.new(ac_demo_params)
    if @ac_demo.save
      redirect_to ac_demos_path
    else
      render 'new'
    end
  end

  def show
  end

  def edit
  end

  def update
    if @ac_demo.update(ac_demo_params)
      redirect_to ac_demos_path
    else
      render 'edit'
    end
  end

  def destroy
    @ac_demo.destroy
    redirect_to ac_demos_path
  end

  private

    def ac_demo_params
      params.require(:ac_demo).permit(:title, :text, :author)
    end

    def demo
      @ac_demo = AcDemo.find(params[:id])
    end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/ar_controller.rb
class ArController < ApplicationController

  def home
  end

  
  def has_one
    @user = HasOne1.first
    @business = HasOneB.first
  end

  def has_many
    @user = Userhm.find(1)
    @doctors = Doctor.all
    @doctor1 = Doctor.find(1)
    @doctor2 = Doctor.find(2)
  end

  def has_many_through
    @couple = Couple.find(1)
    @vendors = Vendor.all
    @vendor = Vendor.find(1)
    @couples = Couple.all
    @contract = Contract.first
  end

end

app/controllers/gem_demos_controller.rb
class GemDemosController < ApplicationController
  before_action :demo, only: [:show, :edit, :update, :destroy]

  def form_populator
    first_name = Faker::Name.first_name
    last_name = Faker::Name.last_name
    birth_date = Faker::Date.backward(36500)
    address = Faker::Address.street_address
    city = Faker::Address.city
    state = Faker::Address.state
    zip = Faker::Address.zip
    render json: {first_name: first_name, last_name: last_name, birth_date: birth_date, address: address, city: city, state: state, zip: zip}
  end

  def index
    @gem_demo = GemDemo.all
  end

  def new
    @gem_demo = GemDemo.new
  end

  def create
    @gem_demo = GemDemo.new(gem_demo_params)
    if @gem_demo.save
      redirect_to gem_demos_path
    else
      render 'new'
    end
  end

  def show
  end

  def edit
  end

  def update
    if @gem_demo.update(gem_demo_params)
      redirect_to gem_demos_path
    else
      render 'edit'
    end
  end

  def destroy
    @gem_demo.destroy
    redirect_to gem_demos_path
  end

  private

  def gem_demo_params
    params.require(:gem_demo).permit(:first_name, :last_name, :birthdate, :address, :city, :state, :zip)
  end

  def demo
    @gem_demo = GemDemo.find(params[:id])
  end



end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  end

  def development
  end

  def html
  end
end

app/helpers/ac_demos_helper.rb
module AcDemosHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/ar_helper.rb
module ArHelper
end

app/helpers/gem_demos_helper.rb
module GemDemosHelper
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/ac_demos/_form.html.haml
= form_for @ac_demo do |f|
  = f.label :title, class: 'active'
  = f.text_field :title, placeholder: 'This is a text field!'
  = f.label :author, class: 'active'
  = f.text_field :author, placeholder: 'Another text field!'
  = f.label :text, class: 'active'
  = f.text_field :text, placeholder: 'This is a text area, a user can use this to type larger bodies of text. Its even resizable!'

  =f.submit 'Submit'

app/views/ac_demos/edit.html.haml
.container
  .main_head
    %h1 Edit Entry: #{@ac_demo.title}!
  %hr
  = render(partial: 'form')
  %hr
  = link_to 'Back', ac_demos_home_path

app/views/ac_demos/home.html.haml
.container
  .main_head
    %h1 Learn How the Action Controller Works!
  %hr
  %ul
    %li - Rails uses a controller base called the Action Controller to route users to views and to manipulate the database in order to populate said views.
    %li - A controller inherits characteristics from the Action Controller.
    %li - Inside a controller, database information is often gathered and stored in variables, which is then used in the view presented to the user.
    %li - One of the most common uses of methods in a controller is CRUD actions: Creating, Reading, Updating, and Destroying data.
    %li - Try clicking the method names in the sample controller.rb file below to learn more about some basic controller actions!
  %hr

  %p
    def
    = link_to 'index', ac_demos_path
    %br
    @posts = Post.all
    %br
    end
    %br
    %br
    - if @ac_demos.any?
      def
      = link_to 'show', ac_demo_path(@ac_demos.first)
      %br
      @post = Post.find(params[:id])
      %br
      end
      %br
      %br
    def
    = link_to 'new', new_ac_demo_path
    %br
    @post = Post.new
    %br
    end
    %br
    %br
    def create
    %br
    @post = Post.new(post_params)
    %br
    if @post.save
    %br
    redirect_to posts_path
    %br
    else
    %br
    render :new
    %br
    end
    %br
    %br
    - if @ac_demos.any?
      def
      = link_to 'edit', edit_ac_demo_path(@ac_demos.last)
      %br
      @post = Post.find(params[:id])
      %br
      end
      %br
      %br
      def @update
      %br
      @post = Post.find(params[:id])
      %br
      if @post.update(post_params)
      %br
      redirect_to posts_path
      %br
      else
      %br
      render :edit
      %br
      end
      %br
      %br
      def
      = link_to 'destroy', ac_demo_path(@ac_demos.last), method: :delete, data: {confirm: "Delete?"}
      %br
      @post = Post.find(params[:id])
      %br
      @post.destroy
      %br
      end
      %br
      %br
    private
    %br
    %br
    def post_params
    %br
    params.require(:post).permit(:title, :author, :text)
    %br
    end
    %br
    %br
  %br

app/views/ac_demos/index.html.haml
.container
  .main_head
    %h1 Index View
  %hr
  %ul
    %li - In this index view, you have access to the entire database table from a variable set in the index method of the controller.
    %li - This variable, which contains every row from the model, can be iterated over to populate the index view with content and links to row specific paths.
  %hr
  - if @ac_demos.any?
    %ul
      - @ac_demos.each do |demo|
        %li
          = demo.title
          = link_to '@show', ac_demo_path(demo)
          = link_to '@edit', edit_ac_demo_path(demo)
          = link_to '@destroy', ac_demo_path(demo), method: :delete, data: {confirm: "Delete?"}
  - else
    %h4 There isn't any content here yet! Head to @new to create some!
  %hr
  = link_to '@new', new_ac_demo_path
  |
  = link_to 'Back', ac_demos_home_path

app/views/ac_demos/new.html.haml
.container
  .main_head
    %h1 Try Creating a New Entry!
  %hr
  = render(partial: 'form')
  %hr
  = link_to 'Back', ac_demos_home_path

app/views/ac_demos/show.html.haml
.container
  .main_head
    %h1 Show View
  %hr
  %ul
    %li - In this show view, you have access to a specific instance of the model, rather than the entire collection of objects represented by the whole database table.
  %hr
  %h3
    = @ac_demo.title
  %p
    By:
    = @ac_demo.author
    %br
    = @ac_demo.text
  %hr
  = link_to 'Back', ac_demos_home_path

app/views/ar/belongs_to.html.haml
%h1 Ar#belongs_to
%p Find me in app/views/ar/belongs_to.html.haml

app/views/ar/has_many.html.haml
.container
  .main_head
    %h1.center
      Learn about Has_Many Associations!
  %hr
    %p.hm-intro.hide
      An association that is used commonly is a has many association. In the following example, #{@user.name} has many doctors. These include #{@doctor1.name} and #{@doctor2.name}. Notice that #{@user.name} user id is #{@user.id}. If we look at the Doctors Table, they have the same user id as the first table but different individual id's. This is how one "User" can have many Doctor's.
  %hr
    .center
      %a.hm-reveal.centerwaves-effect.waves-light.btn-large
        %i.material-icons.left> games
        Click for awesomeness
      .row
        .col.s12.m5
          %table.hm-user-table.hide
            %thead
              %tr
                %th{"data-field" => "User Id"} User Id
                %th{"data-field" => "User Name"} Name
                %th{"data-field" => "Age"} Age
              %tbody
                %tr
                  %td
                    = @user.id
                  %td
                    = @user.name
                  %td
                    = @user.age

        .col.s12.m7
          %table.hm-doctor-table.hide
            %thead
              %tr
                %th{"data-field" => "User Id"} User Id
                %th{"data-field" => "Doctor Id"} Doctor Id
                %th{"data-field" => "Doctor Name"} Doctor name
                %th{"data-field" => "Doctor function"} Doctor Type
              %tbody
                %tr
                  - @doctors.each do|doctor|
                    %td
                      = doctor.userhm_id
                    %td
                      = doctor.id
                    %td
                      = doctor.name
                    %td
                      = doctor.phone_number
                    %tr
  = link_to 'Back to Active Record Home', ar_home_path

app/views/ar/has_many_through.html.haml
.container
  .main_head
    %h1.center
      Learn about Has_Many_Through Associations!
  %hr
    %p.hmt-intro.hide
      An association that is used commonly is a has many through association. In the following example, #{@couple.name} have many vendors; One of which is #{@vendor.name}. Notice that in the second set of tables. #{@vendor.name} is the vendor this time. #{@vendor.name} also happens to have #{@couple.name} as a couple as well. This is made possible through a third table(model) named "Contracts". The function of the third table is to function as a through table with the same id's. In essence, one could simply call "Couple.find(1).vendors".
  %hr
    .center
      %a.hmt-reveal.centerwaves-effect.waves-light.btn-large
        %i.material-icons.left> games
        Click for awesomeness
      .row
        .col.s12.m6
          %table.hmt-couple.bordered.hide
            %thead
              %tr
                %th{"data-field" => "Couple Id"} Couple Id
                %th{"data-field" => "name"} Name
                %th{"data-field" => "Wedding Date"} Wedding Date
              %tbody
                %tr
                  %td
                    = @couple.id
                  %td
                    = @couple.name
                  %td
                    = @couple.wedding_date
        .col.s12.m6
          %table.hmt-vendor.bordered.hide
            %thead
              %tr
                %th{"data-field" => "Vendor Id"} Vendor Id
                %th{"data-field" => "Vendor Name"} Vendor name
                %th{"data-field" => "Vendor function"} Vendor Type
              %tbody
                %tr
                  - @vendors.each do|vendor|
                    %td
                      = vendor.id
                    %td
                      = vendor.name
                    %td
                      = vendor.function
                    %tr

      .row
        .col.s12.m6
          %table.hmt-vendor.bordered.hide
            %thead
              %tr
                %th{"data-field" => "Vendor Id"} Vendor Id
                %th{"data-field" => "Vendor Name"} Vendor Name
                %th{"data-field" => "Vendor Location"} Vendor Location
                %th{"data-field" => "Vendor function"} Vendor Type
              %tbody
                %tr
                  %td
                    = @vendor.id
                  %td
                    = @vendor.name
                  %td
                    = @vendor.location
                  %td
                    = @vendor.function
        .col.s12.m6
          %table.hmt-couple.bordered.hide
            %thead
              %tr
                %th{"data-field" => "Couple Id"} Couple Id
                %th{"data-field" => "Couple Name"} Couple Name
                %th{"data-field" => "Couple Wedding Date"} Couple Wedding Date
              %tbody
                %tr
                  - @couples.each do|couple|
                    %td
                      = couple.id
                    %td
                      = couple.name
                    %td
                      = couple.wedding_date
                    %tr
  %br
  %hr
    .row
      .col.s12.m12
        %h3.contract-intro.center.hide
          Contract Table
        .col.s12.m8.offset-m2
          %table.hmt-contract.bordered.hide
            %thead
              %tr
                %th.center-align{"data-field" => "Contract Id"} Contract Id
                %th.center-align{"data-field" => "Vendor Id"} Vendor Id
                %th.center-align{"data-field" => "Couple Id"} Couple id
              %tbody
                %tr
                  %td.center-align
                    = 1
                  %td.center-align
                    = 1
                  %td.center-align
                    = 1
                %tr
                  %td.center-align
                    = 2
                  %td.center-align
                    = 1
                  %td.center-align
                    = 2
                %tr
                  %td.center-align
                    = 3
                  %td.center-align
                    = 1
                  %td.center-align
                    = 1
                %tr
                  %td.center-align
                    = 4
                  %td.center-align
                    = 1
                  %td.center-align
                    = 2

  = link_to 'Back to Active Record Home', ar_home_path

app/views/ar/has_one.html.haml
.container
  .main_head
    %h1.center
      Learn about Has_one Associations!
  %hr
    %p.h-one-intro.hide
      An association that is used on occasion is a has one association. In the following example, #{@user.name} has one business. Notice that #{@user.name}'s user id is #{@user.id}. In the business table, an attritube exists called user_id. This id matches #{@user.name}'s user id, so that when #{@user.name} created his business he took his user id with him. In active record, one could simply say User.find_by(name: 'joker').business.
  %hr
    .center
      %a.hone-reveal.centerwaves-effect.waves-light.btn-large
        %i.material-icons.left> games
        Click for awesomeness
      .row
        .col.s12.m6.l6
          %table.h-one-user.hide
            %thead
              %tr
                %th{"data-field" => "User Id"} User Id
                %th{"data-field" => "name"} Name
                %th{"data-field" => "Address"} Address
              %tbody
                %tr
                  %td
                    = @user.id
                  %td
                    = @user.name
                  %td
                    = @user.address
        .col.s12.m6.l6
          %table.h-one-business.hide
            %thead
              %tr
                %th{"data-field" => "User Id"} User Id
                %th{"data-field" => "Business"} Business Id
                %th{"data-field" => "name"} Name
                %th{"data-field" => "Address"} Address
              %tbody
                %tr
                  %td
                    = @business.has_one1_id
                  %td
                    = @business.id
                  %td
                    = @business.name
                  %td
                    = @business.address

  = link_to 'Back to Active Record Home', ar_home_path

app/views/ar/home.html.haml
.container
  .main_head
    %h1.center
      Learn about Associations
  %hr
    %p
      Rails Active Record makes  multiple associations a breeze. With Active Record associations, we can streamline these  operations by declaratively telling Rails that there is a connection between  models.
  %hr
    %row
      .center
        = link_to 'Has One Association', ar_one_path
        |
        = link_to 'Has Many Association', ar_hm_path
        |
        = link_to 'Has Many Through Association', ar_hm_through_path

app/views/gem_demos/_gemactions.html.haml
= link_to "my link", "", :onclick => "my_function(); return false"
%p not sure if we want above or below link...
%a{href: '#', onclick: 'my_function(); return false;'} my link

app/views/gem_demos/_gemform.html.haml
%br
%h1 See Faker In Action!
= form_for @gem_demo do |f|
  = f.label :first_name
  = f.text_field :first_name

  = f.label :last_name
  = f.text_field :last_name

  = f.label :birthdate
  = f.text_field :birthdate

  = f.label :address
  = f.text_field :address

  = f.label :city
  = f.text_field :city

  = f.label :state
  = f.text_field :state

  = f.label :zip
  = f.text_field :zip
  = f.submit "Submit"
%br
  %button.populate.btn
    Use Faker!

app/views/gem_demos/_gempagelinks.html.haml
.center
  %hr
  = link_to 'New Gem Demo', new_gem_demo_path, class:'btn'
  |
  = link_to 'Index of Gems', gem_demos_path, class: 'btn '
  %hr
  %br

app/views/gem_demos/edit.html.haml
.container
  .main_head
    %h1 Edit your Gem Demos
  = render 'gemform'

  = render 'gempagelinks'

app/views/gem_demos/index.html.haml
.container
  .main_head
    %h1.center
      Check out all the Faked Users!
  %br
    .row
      .col.s12
        .row
          - @gem_demo.each do |demo|
            .col.m6
              .card.fake-user.red.darken-1
                .card-content.white-text
                  %span.card-title
                    .center
                      Faked User!
                  %ul
                    %li
                      %span
                        First Name :
                        = demo.first_name
                    %li
                      %span
                        Last Name :
                        = demo.last_name
                    %li
                      %span
                        Birth Date :
                        = demo.birthdate
                    %li
                      %span
                        Address :
                        = demo.address
                    %li
                      %span
                        City :
                        = demo.city
                    %li
                      %span
                        State :
                        = demo.state
                    %li
                      %span
                        Zip :
                        = demo.zip

  = render 'gempagelinks'


  -# <div class="row">
  -#       <div class="col s12 m6">
  -#         <div class="card blue-grey darken-1">
  -#           <div class="card-content white-text">
  -#             <span class="card-title">Card Title</span>
  -#             <p>I am a very simple card. I am good at containing small bits of information.
  -#             I am convenient because I require little markup to use effectively.</p>
  -#           </div>
  -#           <div class="card-action">
  -#             <a href="#">This is a link</a>
  -#             <a href="#">This is a link</a>
  -#           </div>
  -#         </div>
  -#       </div>
  -#     </div>

  -# $('#gem_demo_first_name').val(data.first_name)
  -# $('#gem_demo_last_name').val(data.last_name)
  -# $('#gem_demo_birthdate').val(data.birth_date)
  -# $('#gem_demo_address').val(data.address)
  -# $('#gem_demo_city').val(data.city)
  -# $('#gem_demo_state').val(data.state)
  -# $('#gem_demo_zip').val(data.zip)

  -# .div.col.s12.m4
  -#   .div.card.small.white
  -#     .div.black.text
  -#       .span.card-title.amber-text.text-accent-3 = demo.first_name 's Info:
  -#       %p First Name: = demo.first_name
  -#       %p Last Name: = demo.last_name
  -#       %p Description: = demo.address
  -#       %p Gender: = demo.zip
  -#       .div.card-action.center.blue.darken-2
  -#         %p#show-user.btn.tooltipped{"data-position" => "right"}{"data-delay"=>'50'}{"data-tooltip"=>'Click to interact with = user.first_name'}= link_to 'User\'s profile', user_path(user)

app/views/gem_demos/new.html.haml
.container
  = render 'gemform'
  %br
  = render 'gempagelinks'

app/views/gem_demos/show.html.haml
.container
  .main_head
    %h1 Details on a GemDemo
  %p make a loop to show gem demo stuff here if wanted?

  = render 'gempagelinks'

app/views/layouts/_navbar.html.haml
.nav-wrapper
  %ul.side-nav.fixed.hide-on-med-and-down
    %li
      %h1 Wizard of Rails
      %hr
    %li
      = link_to "Home", root_path
    %li
      = link_to "HTML", static_pages_html_path
    %li
      = link_to "Testing", static_pages_development_path
    %li
      = link_to "Active Record", ar_home_path
    %li
      = link_to "Action Controller", ac_demos_home_path
    %li
      = link_to "Gems", gem_demos_path
  %a.hide-on-large-only.button-collapse{"data-activates" => "mobile-demo", :href => "#", style: 'color: black'}
    %i.material-icons
      menu
  %ul#mobile-demo.side-nav
    %li
      %h1 Wizard of Rails
      %hr
    %li
      = link_to "Home", root_path
    %li
      = link_to "HTML & CSS", static_pages_html_path
    %li
      = link_to "Testing", static_pages_development_path
    %li
      = link_to "Active Record", ar_home_path
    %li
      = link_to "Action Controller", ac_demos_home_path
    %li
      = link_to "Gems", gem_demos_path

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>WizardOfRails</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet">
  <%= csrf_meta_tags %>
  <link href="https://fonts.googleapis.com/icon?family=Material+Icons" rel="stylesheet"> 
</head>
<body>
  <header>
    <%= render 'layouts/navbar' %>
  </header>
  <main>
    <%= yield %>
  </main>
</body>
</html>

app/views/static_pages/development.html.haml
.container
  .main_head
    %h1.center-align
      Testing
    %hr
    %br
    %br
    %h5.center-align
      Why Test Your code ?
    %p.center-align It is important to test your code before pushing it up to production. Testing is vital and can fix future problems they may occur with your code. In rails we are going to mainly focus on testing with RSpec. RSpec is a ruby gem created to shorten testing and make it more simple to understand the syntax. Testing will make you a better developer and could land you a job if you know how to test your code.
    %br
      %h5.center-align
        Testing with RSpec
      %p.center-align
        RSpec is a behavior driven framework for Ruby. RSpec can be used to test our models and controllers in isolation and scoped to their context. RSpec tests are written very closely to the english language to aid in readability and maintainability. You can look at an RSpec test and easily understand what it is testing and what the output should be. Testing Models with RSpec is the best place to start learning the RSpec syntax.  Models are the easiest to test and also provide the most core functionality to a Rails app.
      %br
    %h5.center-align
      TDD vs BDD
    %h5.center-align
      TDD (Test-Driven Development)
    %hr
    %ol.center-align
      %li.center-align
        First the developer writes some tests.
      %br
      %li.center-align
        The developer then runs those tests which fail because none of those features are actually implemented.
      %br
      %li.center-align
        Next the developer actually implements those tests in code.
      %br
      %li.center-align
        If the developer writes his code well, then the in next stage he will see his tests pass.
      %br
      %li.center-align
        The developer can then refactor his code, add comments, clean it up as he wishes because the developer knows that if the new code breaks something, then the tests will alert him by failing.
      %br
      %br
      %h5.center-align
        BDD (Behavior-Driven Development)
      %hr
      %br
      %ol.center-align
        %li.center-align
          The developer specifies what functions the site should have
        %br
        %li.center-align
          The developer then writes tests based on what functions the site will have
        %br
        %li.center-align
          The developer will then run the tests to make sure the site functions the way it should
        %br
        %br

app/views/static_pages/home.html.haml
.container
  .main_head
    %h1.center-align
      Wizard of Rails
  %hr
  %br
  %br
  %h5.center-align
    Master your programming skills
  %p.center-align
    Welcome to Wizard of Rails a site created to help individuals build their programming skills and become better developers. We welcome all skill levels, whether you are a beginner or a senior developer we want to welcome all and hope to help anyone.
  %br
  %br
  %h5.center-align
    What We Teach
  %p.center-align
    Wizard of Rails will take you through live examples and we cover many topics such as HTML, Javascript, JQuery & Ajax. We will focus on teaching Rails and cover Associations in Rails, Ruby Gems, Active Record, Action Controllers, and testing with RSpec.
  %br
  %br
  %h5.center-align
    About us
  %p.center-align
    We are a group of 4 who are attending an 11 week long fullstack coding bootcamp called DevPoint Labs that resides in center SLC, Utah. DevPoint Labs offers a fullstack course that focuses on Ruby on Rails. They train students to become Junior Developers and cram so much information into the students to prepare them to land a Junior Dev position.
  %br
  %br
  %table.row.col.s12.m6
    %thead
      %tr
      %th{"data-field" => "Parker"} Parker
      %th{"data-field" => "Trevor"} Trevor
      %th{"data-field" => "Christian"} Christian
      %th{"data-field" => "Scot"} Scot
    %tbody
      %tr
        %td
          %img.materialboxed{:src => "https://avatars0.githubusercontent.com/u/13872438?v=3&s=460", :width => "150"}/
          %a{href: "https://github.com/bondparkerbond", target: "_blank"}
            find me on Github
          %br
          %a{href: "https://www.linkedin.com/pub/parker-bond/102/790/181", target: "_blank"}
            find me on linked in
        %td
          %img.materialboxed{:src => "https://avatars1.githubusercontent.com/u/13872431?v=3&s=460", :width => "150"}/
          %a{href: "https://github.com/tslater3", target: "_blank"}
            find me on Github
          %br
          %a{href: "https://www.linkedin.com/pub/trevor-slater/8a/414/718", target: "_blank"}
            find me on linked in
        %td
          %img.materialboxed{:src => "https://avatars0.githubusercontent.com/u/13805932?v=3&s=460", :width => "150"}/
          %a{href: "https://github.com/cef2010", target: "_blank"}
            find me on Github
          %br
          %a{href: "https://www.linkedin.com/pub/christian-fuller/106/88b/1b0", target: "_blank"}
            find me on linked in
        %td
          %img.materialboxed{:src => "https://media.licdn.com/mpr/mpr/shrinknp_400_400/AAEAAQAAAAAAAAWBAAAAJDFlODM2ZWM3LWUxNDAtNDUwYi1hN2UzLTA2NWFkMzU3MWY5Mw.jpg", :width => "150"}/
          %a{href: "https://github.com/Scotchard22", target: "_blank"}
            find me on Github
          %br
          %a{href: "https://www.linkedin.com/pub/scot-chard/bb/850/721", target: "_blank"}
            find me on linked in

  %br
  %br

app/views/static_pages/js.html.haml
.container
  .main_head
    %h2.center-align
      Javascript, Jquery, & Ajax
  %hr